name: Create Release
on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get version from package.json
        id: pkg_version
        run: |
          echo "VERSION=$(npm pkg get version | tr -d '"')" >> $GITHUB_OUTPUT
      - name: Create Relese
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="v${{ steps.pkg_version.outputs.VERSION }}"
          if gh release view "$VERSION" >/dev/null 2>&1; then
            echo "Release $VERSION already exists. Skipping."
          else
            gh release create "$VERSION" --title "$VERSION" --generate-notes
          fi
